
session_proc_lfp = struct();

% folders = {'Y:\Projects\PPC_pulv_body_signals\ephys\LFP_TFA_results\Magnus_20190124', ...
%     'Y:\Projects\PPC_pulv_body_signals\ephys\LFP_TFA_results\Magnus_20190314'...
%     };
folders = {'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170622', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170629', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170707', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170713', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170720', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170802', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170804', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20170818', ...
    'C:\Data\MIP_timefreq_analysis\LFP_timefrequency_analysis\Data\LFP_TFA_Results\18-Apr-2019\ver_SN_0.1\Lin_20171012'};
    %'Y:\Projects\PPC_pulv_body_signals\ephys\LFP_TFA_results\Magnus_20190131', ...
    %'Y:\Projects\PPC_pulv_body_signals\ephys\LFP_TFA_results\Magnus_20190213'};

for i = 1:length(folders)
    matfiles = dir(fullfile(folders{i}, '*.mat'));
    sites = [];
    for j = 1:length(matfiles)
        disp(fullfile(folders(i), matfiles(j).name));
        load(fullfile(folders{i}, matfiles(j).name))
        sites  = [sites; site_lfp];
        
    end
    session_proc_lfp(i).sites = sites';
end
    